services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend/src/:/app/src # synchroniser dossier frontend/src avec app/src (défini dans Dockerfile du frontend)

  backend:
    build: ./backend 
    ports:
    # - "3000:3000"  # Express REST API
    - "4200:4200"  # Apollo Server GraphQL
    volumes:
      - ./backend/data:/app/data
      - ./backend/src/:/app/src # synchroniser dossier backend/src avec app/src (défini dans Dockerfile du backend)